// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alex/projects/ofm-microservices/ofm-user-service/internal/presentation/event_broker/type.go
//
// Generated by this command:
//
//	mockgen -source=/home/alex/projects/ofm-microservices/ofm-user-service/internal/presentation/event_broker/type.go -destination=/home/alex/projects/ofm-microservices/ofm-user-service/internal/presentation/event_broker/nats/event_broker_mock_test.go -package=nats
//

// Package nats is a generated GoMock package.
package nats

import (
	context "context"
	reflect "reflect"
	config "user-service/config"
	event_broker "user-service/internal/presentation/event_broker"

	gomock "go.uber.org/mock/gomock"
)

// MockEventBroker is a mock of EventBroker interface.
type MockEventBroker struct {
	ctrl     *gomock.Controller
	recorder *MockEventBrokerMockRecorder
	isgomock struct{}
}

// MockEventBrokerMockRecorder is the mock recorder for MockEventBroker.
type MockEventBrokerMockRecorder struct {
	mock *MockEventBroker
}

// NewMockEventBroker creates a new mock instance.
func NewMockEventBroker(ctrl *gomock.Controller) *MockEventBroker {
	mock := &MockEventBroker{ctrl: ctrl}
	mock.recorder = &MockEventBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBroker) EXPECT() *MockEventBrokerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventBroker) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockEventBrokerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventBroker)(nil).Close))
}

// Publish mocks base method.
func (m *MockEventBroker) Publish(ctx context.Context, subject string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventBrokerMockRecorder) Publish(ctx, subject, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventBroker)(nil).Publish), ctx, subject, payload)
}

// RunPullConsumer mocks base method.
func (m *MockEventBroker) RunPullConsumer(ctx context.Context, cfg config.PullConsumerConfig, handler event_broker.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPullConsumer", ctx, cfg, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunPullConsumer indicates an expected call of RunPullConsumer.
func (mr *MockEventBrokerMockRecorder) RunPullConsumer(ctx, cfg, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPullConsumer", reflect.TypeOf((*MockEventBroker)(nil).RunPullConsumer), ctx, cfg, handler)
}

// Subscribe mocks base method.
func (m *MockEventBroker) Subscribe(ctx context.Context, subject string, handler event_broker.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, subject, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventBrokerMockRecorder) Subscribe(ctx, subject, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventBroker)(nil).Subscribe), ctx, subject, handler)
}
